### ISSUE TITLE
SSH access settings not available

### ISSUE THREAD

**Issue by mcnesium** [Nitrokey/nextbox-app#13]
Just setting up my new Nextbox. I would like to use ssh/rsync to transfer all the data from the old storage to it. [In the docs](https://docs.nitrokey.com/nextbox/faq.html#software) it says that it can be set up in the Nextbox app. However, I am not seeing any settings that would allow me to do so:

<img src="https://user-images.githubusercontent.com/476060/125198463-4196b400-e262-11eb-90b5-edbb11b53668.png" width="100%" height="100%"/>

I have set up a domain using the backwards proxy feature. Do I need to enable something else? This is Nextbox App v1.0.4

**Comment by daringer** [comment]
Ha, that's an unlucky one. Please scroll down inside the navigation on the left side. We use the Nextcloud Vue Toolchain, it's kind of a feature that the left side is separated into two boxes (upper and lower) thus this effect.
